apiVersion: v1
kind: Secret
metadata:
    name: postgres-credentials
type: Opaque
data:
    postgres_user: cG9zdGdyZXM= #postgres
    postgres_password: cGFzc3dvcmQ= #password
    postgres_db_name: cG9zdGdyZXM= #postgres
    postgres_host: cG9zdGdyZXMtc2VydmljZQ== #postgres-service
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata: 
    name: postgres-volume-claim
spec:
    accessModes:
        - ReadWriteOnce
    volumeMode: Filesystem
    resources:
        requests:
            storage: 5Gi
    selector:
       matchLabels: 
            release: "stable"
---
apiVersion: v1
kind: Service
metadata:
    name: obpapi-service
spec:
    selector:
        app: obpapi
    ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: obp-deployment
    labels:
        app: obpapi
spec:
    replicas: 1
    selector:
        matchLabels:
            app: obpapi
    template:
        metadata:
            labels:
                app: obpapi
        spec:
            containers:
            - name: obpapi
              image: chrisjsimpson/obpapi-kube # docker build -t obpapi:1 .
              env:
                - name: DB_USER
                  valueFrom: 
                    secretKeyRef: 
                     name: postgres-credentials
                     key: postgres_user
                - name: DB_PASS
                  valueFrom: 
                    secretKeyRef: 
                     name: postgres-credentials
                     key: postgres_password
                - name: DB_NAME
                  valueFrom: 
                    secretKeyRef: 
                     name: postgres-credentials
                     key: postgres_db_name
                - name: DB_HOST
                  valueFrom: 
                    secretKeyRef: 
                     name: postgres-credentials
                     key: postgres_host
              ports:
              - containerPort: 8080
                name: http
              - containerPort: 5432
                name: postgres
---
apiVersion: v1
kind: Service
metadata:
    name: postgres-service
spec:
    selector:
        app: postgres
    ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres
    labels:
        app: postgres
spec:
    replicas: 1
    selector:
        matchLabels:
            app: postgres
    template:
        metadata:
            labels:
                app: postgres
        spec:
            containers:
            - name: postgres
              image: postgres:11.1-alpine
              env: 
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                     name: postgres-credentials
                     key: postgres_user
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef: 
                     name: postgres-credentials
                     key: postgres_password
              volumeMounts:
              - name: postgres-volume
                mountPath: "/var/lib/postgresql/data"
              ports:
              - containerPort: 5432
            volumes:
                - name: postgres-volume
                  persistentVolumeClaim:
                    claimName: postgres-volume-claim
