apiVersion: apps/v1
kind: Deployment
metadata:
    name: obp-deployment
    labels:
        app: obpapi
spec:
    replicas: 1
    selector:
        matchLabels:
            app: obpapi
    template:
        metadata:
            labels:
                app: obpapi
        spec:
            containers:
            - name: obpapi
              image: chrisjsimpson/obpapi-kube # docker build -t obpapi-kube .
              resources:
                requests:
                  memory: "126Mi"
              env:
                - name: DB_DRIVER
                  valueFrom:
                    secretKeyRef:
                     name: postgres-credentials
                     key: jdbc_driver
                - name: DB_URL
                  valueFrom:
                    secretKeyRef:
                     name: postgres-credentials
                     key: jdbc_driver
                - name: DB_URL
                  valueFrom:
                    secretKeyRef:
                     name: postgres-credentials
                     key: jdbc_url
              ports:
              - containerPort: 8080
                name: http
              - containerPort: 5432
                name: postgres
