kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: postgres-volume-claim
spec:
    accessModes:
        - ReadWriteOnce
    volumeMode: Filesystem
    resources:
        requests:
            storage: 5Gi
