apiVersion: v1
kind: Secret
metadata:
    name: postgres-credentials
type: Opaque
data:
    postgres_user: cG9zdGdyZXM= #postgres
    postgres_password: cGFzc3dvcmQ= #password
    postgres_db_name: cG9zdGdyZXM= #postgres
    postgres_data: L3Zhci9saWIvcG9zdGdyZXNxbC9kYXRhL3BnZGF0YQ== # /var/lib/postgresql/data/pgdata
    jdbc_driver: b3JnLnBvc3RncmVzcWwuRHJpdmVy # org.postgresql.Driver
    jdbc_url: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXMtc2VydmljZTo1NDMyL3Bvc3RncmVzP3VzZXI9cG9zdGdyZXMmcGFzc3dvcmQ9cGFzc3dvcmQ= # jdbc:postgresql://postgres-service:5432/postgres?user=postgres&password=password
