apiVersion: v1
kind: Service
metadata:
    name: obpapi-service
spec:
    selector:
        app: obpapi
    ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
    type: LoadBalancer
